### PR TITLE
Add acs entitlements to prod

### PR DESCRIPTION
**Pull request by bradr5**
Add acs entitlements to prod

### CODE REVIEW

**Comment by Ellen-Yi-Dong** [comment]
Is there a JIRA ticket linked to this PR? I'm just curious if there's a reason why stage isn't being updated? Thank you so much!

**Comment by bradr5** [comment]
> Is there a JIRA ticket linked to this PR? I'm just curious if there's a reason why stage isn't being updated? Thank you so much!

That was a miss on my part, updated. The ticket in question is ROX-16339

**Review by dagbay-rh — APPROVED** [review]
LGTM :rocket: one thing to add is we will have to add the new `acs` bundle to the list of bundles to sync with the features API. Here is an example: https://github.com/RedHatInsights/entitlements-api-go/pull/94/files

This change is in the entitlements repo itself and can be done after this

**Review by Ellen-Yi-Dong — APPROVED** [review]
LGTM!

**Review by lpichler — APPROVED** [review]

**Comment by dagbay-rh** [comment]
gonna merge this, @bradr5 I can take a look at the other PR needed once its up

**Comment by lpichler** [comment]
@bradr5 we added SKUs to stage, can you check it, please ? Let us know once we can add it to production, thanks!

**Pull request merged**
